// <auto-generated />
namespace MonthlyBudgetCalculator.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _18April2015g : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_18April2015g));
        
        string IMigrationMetadata.Id
        {
            get { return "201504182103007_18April2015g"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
